# Generated by Django 5.0.7 on 2024-10-04 16:03

import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("qs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalentry",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
