# Generated by Django 5.0.7 on 2025-02-17 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qs", "0002_alter_journalentry_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="journalentry",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "journal entries",
            },
        ),
    ]
