services:
  django:
    build: .
    env_file: "cmsmc/.env"
    volumes:
      - /var/www/beta.curtmerrill.com/data:/data
      - /var/www/beta.curtmerrill.com/staticfiles:/staticfiles
    ports:
      - "8087:8088"
    restart: unless-stopped
