services:
  django:
    build: .
    env_file: "cmsmc/.env"
    volumes:
      - /host/path/data:/app/data
      - /host/path/staticfiles:/app/staticfiles
    ports:
      - "8088:8088"
    restart: unless-stopped
