# Generated by Django 5.2.4 on 2025-08-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_page_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='subtitle',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
    ]
