# Generated by Django 5.2.4 on 2025-08-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='subtitle',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
    ]
