# Generated by Django 5.0.7 on 2024-09-10 13:48

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="og_image",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
